-- 코드를 작성해주세요
WITH RECURSIVE GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT C.ID, C.PARENT_ID, P.GEN + 1 AS GEN
    FROM ECOLI_DATA C
    JOIN GENERATION P ON C.PARENT_ID = P.ID
)
SELECT COUNT(*) AS COUNT, G.GEN AS GENERATION
FROM GENERATION G
LEFT JOIN ECOLI_DATA C ON G.ID = C.PARENT_ID
WHERE C.PARENT_ID IS NULL
GROUP BY G.GEN
ORDER BY G.GEN;