-- 코드를 입력하세요
WITH TOTAL_ORDER_TABLE AS(
    SELECT F.FLAVOR, SUM(J.TOTAL_ORDER) AS JULY_ORDER, F.TOTAL_ORDER
    FROM FIRST_HALF F
    JOIN JULY J ON F.FLAVOR = J.FLAVOR
    GROUP BY F.FLAVOR, F.TOTAL_ORDER
)
SELECT FLAVOR
FROM (
    SELECT FLAVOR,
    RANK() OVER (ORDER BY JULY_ORDER + TOTAL_ORDER DESC) AS R
    FROM TOTAL_ORDER_TABLE
) RNK
WHERE R <= 3
ORDER BY R ASC;