-- 코드를 작성해주세요
SELECT ITEM.ITEM_ID, ITEM.ITEM_NAME, ITEM.RARITY
FROM ITEM_INFO ITEM
JOIN ITEM_TREE TREE ON ITEM.ITEM_ID = TREE.ITEM_ID
WHERE TREE.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
ORDER BY ITEM.ITEM_ID DESC;