
WITH CARS AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MON, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10' 
AND CAR_ID IN (
    SELECT CAR_ID
    FROM CARS
)
GROUP BY TO_CHAR(START_DATE, 'MM'), CAR_ID
HAVING COUNT(HISTORY_ID) > 0
ORDER BY MON, CAR_ID DESC;