-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT ID, FISH_NAME, LENGTH, 
    RANK() OVER (PARTITION BY INFO.FISH_TYPE ORDER BY LENGTH DESC) RNK
    FROM FISH_INFO AS INFO
    JOIN FISH_NAME_INFO AS NAME ON INFO.FISH_TYPE = NAME.FISH_TYPE
) R
WHERE RNK  = 1
ORDER BY ID;