-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES)
FROM BOOK B
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
    GROUP BY BOOK_ID
) S ON S.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY CATEGORY;