-- 코드를 입력하세요
WITH MAX_PRICE AS(
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('국', '과자', '김치', '식용유')
    GROUP BY CATEGORY
)
SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN MAX_PRICE M ON F.CATEGORY = M.CATEGORY AND F.PRICE = M.PRICE
ORDER BY F.PRICE DESC;