WITH CODES AS (
    SELECT 
    BIT_OR(CASE WHEN NAME = 'PYTHON' THEN CODE END) AS PY,
    BIT_OR(CASE WHEN CATEGORY = 'FRONT END' THEN CODE END) AS FE,
    BIT_OR(CASE WHEN NAME = 'C#' THEN CODE END) AS C
    FROM SKILLCODES
)
SELECT 
CASE 
WHEN (D.SKILL_CODE & C.PY > 0) AND (D.SKILL_CODE & C.FE > 0) THEN 'A'
WHEN D.SKILL_CODE & C.C > 0 THEN 'B'
WHEN D.SKILL_CODE & C.FE > 0 THEN 'C'
END AS GRADE,
D.ID,
D.EMAIL
FROM DEVELOPERS D
CROSS JOIN CODES C
WHERE (D.SKILL_CODE & C.FE > 0) OR (D.SKILL_CODE & C.C > 0)
ORDER BY GRADE, ID;